### ISSUE TITLE
UnitRange is not entirely transparent on usage, and StepRanges don't work.

### ISSUE THREAD

**Issue by Borketh** [oschulz/BitOperations.jl#7]
First issue: arrays start at one in julia, but using a range starting with one with bitops returns a range starting with the second bit.
```julia
julia> bits = 0b1010100010101100
0xa8ac

julia> bget(bits, 1:4)
0x0006

julia> bget(bits, 0:4)
0x000c

julia> (bitstring(bget(bits, 1:4)), bitstring(bget(bits, 0:4)))
("0000000000000110", "0000000000001100")
```

Additionally, StepRanges (declared with `start:step:stop`) do not work. This would be useful to have properly working, for xample with a backwards-stepped range, such as `16:-1:0`
```julia
julia> bget(bits, 1:2:4)
ERROR: MethodError: no method matching bget(::UInt16, ::StepRange{Int64, Int64})
```

**Comment by oschulz** [comment]
> First issue: arrays start at one in julia

Indeed, but for bit ranges, I decided to start with zero. When is comes to bits, zero-based indexing is basically universal (in device documentations, etc.) and the index carries mathematical meaning (2^n).

> Additionally, StepRanges [...] do not work. This would be useful to have, for xample with a backwards-stepped range

I'm not against it, in principle, I just never encountered a use case for it yet. What would you use it for, specifically?

**Comment by Borketh** [comment]
> for bit ranges, I decided to start with zero

Can you at least clarify that in the documentation? I'm sure I wasn't the only one to be thoroughly befuddled by this 😆

> What would you use it for, specifically?

I specifically don't have a use for this *yet*, but even things like negative-stepping – like I mentioned in the original post – may be useful to others.

**Comment by oschulz** [comment]
> Can you at least clarify that in the documentation?

Good idea! Wanna to a pull request?

**Comment by Borketh** [comment]
I can do, yeah. Docs just come from `Documenter.jl`'s parsing of the docstrings, right?

**Comment by oschulz** [comment]
Yes, they do.
